import type { Context } from 'hono'
import { GAME_IDS } from '../../../shared/game-ids.ts'

const VALID_GAME_IDS: ReadonlySet<string> = new Set(GAME_IDS)

// v4 UUID as generated by crypto.randomUUID() on the client
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value)
}

export function isGameId(value: unknown): value is string {
  return typeof value === 'string' && VALID_GAME_IDS.has(value)
}

// Points are bounded by the highest maxPoints in the game registry (1000)
export const MAX_POINTS = 1000
// Times beyond a day are garbage regardless of game
export const MAX_TIME_SECONDS = 86_400

export async function readJson<T>(c: Context): Promise<T | null> {
  try {
    return await c.req.json<T>()
  } catch {
    return null
  }
}
